### PR TITLE
Add cargo clippy to github actions

### PR DESCRIPTION
**Pull request by sandbergja**

### CODE REVIEW

**Comment by berick** [comment]
Hey, mind tweaking the clippy command to run:

`cargo clippy --all --all-features`

This helped me track down some additional errors.

**Comment by berick** [comment]
This is interesting...  It looks like your'e running a newer version of clippy.  When I compile on Ubuntu 22.04 with the rust-all package, it warns that it does not recognize the new `#[allow(clippy::...` additions.  (Also explains why I missed them when I was doing clippy work before).

Because of this, and also just because, I'd like to avoid clippy exceptions where possible.  I'd be happy to modify the code so we can remove the exceptions, unless you want to take a crack at it.

**Comment by sandbergja** [comment]
Makes sense to me, @berick !  I can give it a try, I'll carve out some time on Tuesday to work on it.

**Comment by sandbergja** [comment]
@berick I got those cleaned up, and the unit and live tests are passing for me.  I think it's ready for you to take another look when you have a chance.

**Comment by berick** [comment]
Looks great, thanks!  Today I learned about HashMap::entry::or_default, neat.

**Pull request merged**
