### PR TITLE
Add tests for marc::Subfield::new

### PR DESCRIPTION
**Pull request by sandbergja**

### CODE REVIEW

**Comment by berick** [comment]
Interesting use of `should_panic`.  That's a new one to me.

I'm curious about the use of todo!() in the Err() branch.  Is that meant to convey anything in particular in the context of a unit test or just a way to say "we shouldn't get here anyway so, sure, panic if we do"?

**Comment by sandbergja** [comment]
Thanks, @berick !  It's more the second scenario -- we wanted to add a usage example that used `match`, but then didn't know what to put in `Err`.  We can go back to the drawing board on that one, or if you have any suggestions...

**Comment by berick** [comment]
Got it.  No problem.  The `todo()!` does create the impression the patch is incomplete.  You could make it more explicit with something like:

`Err(e) => panic!("Subfield::new() failed with: {}", e),`

And we know `e` can be coerced into a String (for the panic!() message) since the Err() branch for Subfield::new() is a String.

**Comment by sandbergja** [comment]
Ah, nice!  That makes sense.  We've pushed another commit with that `panic!`.

**Comment by berick** [comment]
Merged to main.  Thanks!

**Pull request closed without merging**
